---
- hosts: web_dev
  vars:
    ansible_ssh_private_key_file: ~/.ssh/***.pem
  remote_user: ec2-user
  roles:
    - { role: user, when: false }

- hosts: web_dev
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
  remote_user: "{{ user_name }}"
  roles:
    - { role: yum_update, when: false }
    - base
    - ruby
    - mysql
    - nginx
