
- name: install rbenv
  git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv

- name: add rbenv path
  lineinfile:
    dest="~/.bash_profile"
    line="export PATH=$HOME/.rbenv/bin:$PATH"

- name: eval rbenv init
  lineinfile:
    dest="~/.bash_profile"
    line='eval "$(rbenv init -)"' #'

- name: install dependencies for ruby-build
  yum: name={{ item }} state=latest
  become: true
  with_items:
    - gcc
    - gcc-c++
    - openssl-devel
    - libyaml-devel
    - libffi-devel
    - readline-devel
    - zlib-devel
    - gdbm-devel
    - ncurses-devel

- name: install ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build

- name: install ruby with rbenv
  shell: bash -lc "rbenv install {{ ruby_version }}"
  ignore_errors: yes
- name: global ruby
  shell: bash -lc "rbenv global {{ ruby_version }}"
- name: rehash rbenv
  shell: bash -lc "rbenv rehash"

- name: install dependency for rails
  become: yes
  yum: name={{ item }} state=latest
  with_items:
    - patch

- name: install bundler
  gem:
    name=bundler
    executable=~/.rbenv/shims/gem
    user_install=False
    version={{ ruby_bundler_version }}


